<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Registrate</name>
   <tag></tag>
   <elementGuidId>9349b2d5-4da4-4efa-8e8d-03439f381426</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btnswitch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/h4/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>40237600-d844-4752-8bde-9ad847ec4b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnswitch</value>
      <webElementGuid>31cc27d8-2c9f-4e57-a5ae-f2d3885e17ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Registrate</value>
      <webElementGuid>ba3dabc8-abf9-4528-bfa0-0e98f3e3e7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;padre&quot;]/div[@class=&quot;card card-body shadow-lg&quot;]/h4[@class=&quot;texto&quot;]/button[@class=&quot;btnswitch&quot;]</value>
      <webElementGuid>bd47a394-3cda-4613-9b34-0891a07c0651</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/h4/button</value>
      <webElementGuid>eabb2837-a2b8-44c6-a849-ff5e42cb8b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicia sesion'])[1]/following::button[1]</value>
      <webElementGuid>8faeaca3-3f4d-41d6-b93e-b68a5dc361f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Registrate']/parent::*</value>
      <webElementGuid>78183405-8283-4a8d-a65a-eea8378d50b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4/button</value>
      <webElementGuid>119ceba2-1582-4d61-b563-17b07e0d02f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Registrate' or . = 'Registrate')]</value>
      <webElementGuid>616a656f-84f4-4293-a202-3ad8404aeec8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
